# Generated by Django 3.1.7 on 2021-04-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0002_auto_20210408_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='title',
            field=models.CharField(default='Title here', max_length=200),
        ),
    ]
